### PR TITLE
Re-add save-prefix on .yarnrc

### PR DESCRIPTION
**Pull request by davidsonsns**
issue #9

### CODE REVIEW

**Comment by davidsonsns** [comment]
hmm no problem @LasaleFamine, I'll update

**Comment by davidsonsns** [comment]
@LasaleFamine hope this is it. I enjoyed the breeding experience for the yeoman, and incusive I had some ideas for the repo. I'll open some issues to validate.

**Comment by LasaleFamine** [comment]
I really appreciate your work, and actually everything is correct, but... I don't want to make it as a choice. I made the generator to be opinionated and the `save-prefix false` is an option I already had on the generator, but due to a `yarn 1.0.0` bug (now solved in  `1.0.2`) and I only wanted to re-enable the option within the `.yarnrc`.
Please, I will not merge the PR with this changes.

If you want to go more deeper into the generator there is the Typescript (issue #5) too.

Thank you for your comprehension.

**Comment by davidsonsns** [comment]
so I really do not understand, I'll see Issue #5  as soon as I can.

**Comment by LasaleFamine** [comment]
It's just about to add the prop 'save-prefix false' within the .yarnrc, under the current 'save-exact true'. For this issue is just this. If you want, just modify the .yarnrc and I will merge this

**Comment by davidsonsns** [comment]
I'm sorry, now that I realized I kept exact instead of prefix. but do you find it interesting to leave the option at the moment of generating in the cli?

**Comment by LasaleFamine** [comment]
I always want both options in my `.yarnrc`:

```
save-exact true
save-prefix false
```

This prevents `yarn`  to save new dependencies with the caret (`^`) that I hate to have. I want the exact version specified within the package.json to be installed as dependency. So this is all about the issue.

**Pull request merged**
